services:
  redis:
    image: redis:7.2-alpine
    container_name: ebank-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ebank-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8.3
    container_name: ebank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ebank
      MYSQL_USER: ebankuser
      MYSQL_PASSWORD: ebankpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ebank-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p12345"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  mysql_data:

networks:
  ebank-network:
    driver: bridge

